// ================= DATI ANNUNCI (REALI) =================
// Annunci reali raccolti da portali pubblici (Daft.ie, Rightmove) via ricerca;
// ogni scheda ha il link alla fonte originale. Coordinate geocodificate (Nominatim).
// Le FOTO sono illustrative: la fonte contiene le foto reali e i dettagli completi.
// Rigenerato dall'agente giornaliero (vedi docs/daily-agent.md).

export const LAST_UPDATED = '2026-08-09'

export const ZONES = [
  'Burtonport (Donegal, IE)',
  'North Berwick (Scozia)',
  'Rosemarkie (Scozia)',
  'East Neuk (Fife, Scozia)',
]

const U = (id, seed) => [
  `https://images.unsplash.com/photo-${id}?w=900&q=60&auto=format&fit=crop`,
  seed,
]

export const IMGS = {
  h1: U('1568605114967-8130f3a36994', 'casa1'), h2: U('1570129477492-45c003edd2be', 'casa2'),
  h3: U('1564013799919-ab600027ffc6', 'casa3'), h4: U('1512917774080-9991f1c4c750', 'casa4'),
  h5: U('1580587771525-78b9dba3b914', 'casa5'), h6: U('1600596542815-ffad4c1539a9', 'casa6'),
  h7: U('1600585154340-be6161a56a0c', 'casa7'), i1: U('1600607687939-ce8a6c25118c', 'int1'),
  i2: U('1600566753086-00f18fb6b3ea', 'int2'), i3: U('1502672260266-1c1ef2d93688', 'int3'),
  i4: U('1522708323590-d24dbb6b0267', 'int4'), i5: U('1560448204-e02f11c3d0e2', 'int5'),
  i6: U('1493809842364-78817add7ffb', 'int6'), v1: U('1583608205776-bfd35f0d9f83', 'villa1'),
  v2: U('1613490493576-7fde63acd811', 'villa2'), v3: U('1613977257363-707ba9348227', 'villa3'),
  h8: U('1600047509807-ba8f99d2cdde', 'casa8'), h9: U('1600585152220-90363fe7e115', 'casa9'),
  i7: U('1600607687920-4e2a09cf159d', 'int7'), i8: U('1600210492486-724fe5c67fb0', 'int8'),
}

export const FEATURES = [
  'Garage', 'Giardino', 'Terreno', 'Da ammodernare',
]

// currency: 'EUR' per l'Irlanda (Burtonport), 'GBP' per la Scozia.
export const LISTINGS = [
  {"id": 1, "title": "Keadue, Burtonport", "type": "Casa indipendente", "contract": "sale", "price": 164950, "currency": "EUR", "size": null, "rooms": 4, "baths": null, "floor": null, "year": null, "energy": null, "zone": "Burtonport (Donegal, IE)", "town": "Burtonport", "addr": "Keadue, Burtonport, Co. Donegal", "lat": 54.9879, "lng": -8.4406, "imgs": ["v2", "h5", "i1"], "feats": [], "desc": "Casa indipendente di 4 camere a Burtonport. Annuncio reale su Daft.ie — apri la fonte per foto, superficie e dettagli completi.", "date": "2026-08-09", "url": "https://www.daft.ie/for-sale/detached-house-keadue-burtonport-co-donegal/3959555"},
  {"id": 2, "title": "Roshine Acres, Burtonport", "type": "Casa indipendente", "contract": "sale", "price": 269000, "currency": "EUR", "size": null, "rooms": 4, "baths": null, "floor": null, "year": null, "energy": null, "zone": "Burtonport (Donegal, IE)", "town": "Burtonport", "addr": "Roshine Acres, Burtonport, Co. Donegal (F94N2DC)", "lat": 54.9879, "lng": -8.4406, "imgs": ["h5", "i1", "h7"], "feats": [], "desc": "Casa indipendente di 4 camere a Burtonport. Annuncio reale su Daft.ie — apri la fonte per foto, superficie e dettagli completi.", "date": "2026-08-09", "url": "https://www.daft.ie/for-sale/detached-house-roshine-acres-burtonport-co-donegal/5631739"},
  {"id": 3, "title": "Milltown, Burtonport", "type": "Casa indipendente", "contract": "sale", "price": 149000, "currency": "EUR", "size": null, "rooms": 3, "baths": null, "floor": null, "year": null, "energy": null, "zone": "Burtonport (Donegal, IE)", "town": "Burtonport", "addr": "Milltown, Burtonport, Co. Donegal (F94A0F8)", "lat": 54.9879, "lng": -8.4406, "imgs": ["i1", "h7", "i5"], "feats": [], "desc": "Casa indipendente di 3 camere a Burtonport. Annuncio reale su Daft.ie — apri la fonte per foto, superficie e dettagli completi.", "date": "2026-08-09", "url": "https://www.daft.ie/for-sale/house-milltown-burtonport-burtonport-co-donegal/6101936"},
  {"id": 4, "title": "Lackenagh, Burtonport", "type": "Casa indipendente", "contract": "sale", "price": 224950, "currency": "EUR", "size": null, "rooms": 4, "baths": null, "floor": null, "year": null, "energy": null, "zone": "Burtonport (Donegal, IE)", "town": "Burtonport", "addr": "Lackenagh, Burtonport, Co. Donegal", "lat": 54.9879, "lng": -8.4406, "imgs": ["h7", "i5", "h1"], "feats": [], "desc": "Casa indipendente di 4 camere a Burtonport. Annuncio reale — vedi la scheda sulla fonte (Daft.ie).", "date": "2026-08-09", "url": "https://www.daft.ie/property-for-sale/burtonport-donegal/houses"},
  {"id": 5, "title": "Dirleton Avenue, North Berwick", "type": "Villa", "contract": "sale", "price": 795000, "currency": "GBP", "size": null, "rooms": 4, "baths": null, "floor": null, "year": null, "energy": null, "zone": "North Berwick (Scozia)", "town": "North Berwick", "addr": "Dirleton Avenue, North Berwick, EH39", "lat": 56.057591, "lng": -2.736473, "imgs": ["i5", "h1", "i3"], "feats": [], "desc": "Villa di 4 camere a North Berwick. Annuncio reale su Rightmove — apri la fonte per foto, superficie e dettagli completi.", "date": "2026-08-09", "url": "https://www.rightmove.co.uk/properties/157250888"},
  {"id": 6, "title": "Links Road, North Berwick", "type": "Appartamento", "contract": "sale", "price": 650000, "currency": "GBP", "size": null, "rooms": 2, "baths": null, "floor": null, "year": null, "energy": null, "zone": "North Berwick (Scozia)", "town": "North Berwick", "addr": "Links Road, North Berwick, EH39", "lat": 56.059435, "lng": -2.730622, "imgs": ["h1", "i3", "h6"], "feats": [], "desc": "Appartamento di 2 camere a North Berwick. Annuncio reale su Rightmove — apri la fonte per foto, superficie e dettagli completi.", "date": "2026-08-09", "url": "https://www.rightmove.co.uk/properties/173616113"},
  {"id": 7, "title": "Maxwell Road, Dirleton", "type": "Casa indipendente", "contract": "sale", "price": 280000, "currency": "GBP", "size": null, "rooms": 2, "baths": null, "floor": null, "year": null, "energy": null, "zone": "North Berwick (Scozia)", "town": "Dirleton", "addr": "8 Maxwell Road, Dirleton, EH39 5EY", "lat": 56.044255, "lng": -2.780859, "imgs": ["i3", "h6", "i7"], "feats": [], "desc": "Casa indipendente di 2 camere a Dirleton. Annuncio reale su Rightmove — apri la fonte per foto, superficie e dettagli completi.", "date": "2026-08-09", "url": "https://www.rightmove.co.uk/properties/142605404"},
  {"id": 8, "title": "The Swallows, Rosemarkie", "type": "Casa indipendente", "contract": "sale", "price": 620000, "currency": "GBP", "size": null, "rooms": 6, "baths": null, "floor": null, "year": null, "energy": null, "zone": "Rosemarkie (Scozia)", "town": "Rosemarkie", "addr": "The Swallows, Rosemarkie, Fortrose, IV10", "lat": 57.601784, "lng": -4.139722, "imgs": ["h6", "i7", "h2"], "feats": ["Garage", "Giardino", "Terreno", "Da ammodernare"], "desc": "Casa indipendente di 6 camere a Rosemarkie, sul Black Isle. Da parziale ammodernamento; la fonte indica doppio garage con officina, giardino e terreno. Annuncio reale su Rightmove — apri la fonte per foto, superficie e dettagli completi.", "date": "2026-08-09", "url": "https://www.rightmove.co.uk/properties/153623714"},
  {"id": 9, "title": "Upper West Wing, Rosemarkie", "type": "Casa indipendente", "contract": "sale", "price": 550000, "currency": "GBP", "size": null, "rooms": 4, "baths": null, "floor": null, "year": null, "energy": null, "zone": "Rosemarkie (Scozia)", "town": "Rosemarkie", "addr": "Rosemarkie, IV10", "lat": 57.590688, "lng": -4.114306, "imgs": ["i7", "h2", "i6"], "feats": [], "desc": "Casa indipendente di 4 camere a Rosemarkie. Annuncio reale — vedi la scheda sulla fonte (Rightmove).", "date": "2026-08-09", "url": "https://www.rightmove.co.uk/property-for-sale/Rosemarkie.html"},
  {"id": 10, "title": "Greenside House, Courthill Road, Rosemarkie", "type": "Casa indipendente", "contract": "sale", "price": 365000, "currency": "GBP", "size": null, "rooms": 4, "baths": null, "floor": null, "year": null, "energy": null, "zone": "Rosemarkie (Scozia)", "town": "Rosemarkie", "addr": "Courthill Road, Rosemarkie, IV10", "lat": 57.589828, "lng": -4.117584, "imgs": ["h2", "i6", "v3"], "feats": [], "desc": "Casa indipendente di 4 camere a Rosemarkie. Annuncio reale — vedi la scheda sulla fonte (Rightmove).", "date": "2026-08-09", "url": "https://www.rightmove.co.uk/property-for-sale/Rosemarkie.html"},
  {"id": 11, "title": "Holmes Cottage, High Street, Fortrose", "type": "Cottage", "contract": "sale", "price": 224000, "currency": "GBP", "size": null, "rooms": 3, "baths": null, "floor": null, "year": null, "energy": null, "zone": "Rosemarkie (Scozia)", "town": "Fortrose", "addr": "40 High Street, Fortrose, IV10", "lat": 57.5801, "lng": -4.1332, "imgs": ["i6", "v3", "i8"], "feats": [], "desc": "Cottage di 3 camere a Fortrose. Annuncio reale — vedi la scheda sulla fonte (Rightmove).", "date": "2026-08-09", "url": "https://www.rightmove.co.uk/property-for-sale/Fortrose.html"},
  {"id": 12, "title": "Station Road, St Monans", "type": "Casa indipendente", "contract": "sale", "price": 525000, "currency": "GBP", "size": null, "rooms": 5, "baths": null, "floor": null, "year": null, "energy": null, "zone": "East Neuk (Fife, Scozia)", "town": "St Monans", "addr": "Station Road, St. Monans, KY10", "lat": 56.206582, "lng": -2.766321, "imgs": ["v3", "i8", "h8"], "feats": [], "desc": "Casa indipendente di 5 camere a St Monans. Annuncio reale su Rightmove — apri la fonte per foto, superficie e dettagli completi.", "date": "2026-08-09", "url": "https://www.rightmove.co.uk/properties/166079381"},
  {"id": 13, "title": "Marketgate North, Crail", "type": "Casa indipendente", "contract": "sale", "price": 525000, "currency": "GBP", "size": null, "rooms": 5, "baths": null, "floor": null, "year": null, "energy": null, "zone": "East Neuk (Fife, Scozia)", "town": "Crail", "addr": "Marketgate North, Crail, KY10", "lat": 56.261908, "lng": -2.624842, "imgs": ["i8", "h8", "i4"], "feats": [], "desc": "Casa indipendente di 5 camere a Crail. Annuncio reale su Rightmove — apri la fonte per foto, superficie e dettagli completi.", "date": "2026-08-09", "url": "https://www.rightmove.co.uk/properties/162908468"},
  {"id": 14, "title": "Easter Cottage, Shoregate, Crail", "type": "Cottage", "contract": "sale", "price": 350000, "currency": "GBP", "size": null, "rooms": 2, "baths": null, "floor": null, "year": null, "energy": null, "zone": "East Neuk (Fife, Scozia)", "town": "Crail", "addr": "27 Shoregate, Crail, KY10", "lat": 56.257814, "lng": -2.627616, "imgs": ["h8", "i4", "v1"], "feats": [], "desc": "Cottage di 2 camere a Crail. Annuncio reale su Rightmove — apri la fonte per foto, superficie e dettagli completi.", "date": "2026-08-09", "url": "https://www.rightmove.co.uk/properties/150142016"},
  {"id": 15, "title": "Roomebay Crescent, Crail", "type": "Bungalow", "contract": "sale", "price": 500000, "currency": "GBP", "size": null, "rooms": 3, "baths": null, "floor": null, "year": null, "energy": null, "zone": "East Neuk (Fife, Scozia)", "town": "Crail", "addr": "Roomebay Crescent, Crail, KY10", "lat": 56.2601, "lng": -2.6276, "imgs": ["i4", "v1", "i2"], "feats": [], "desc": "Bungalow di 3 camere a Crail. Annuncio reale su Rightmove — apri la fonte per foto, superficie e dettagli completi.", "date": "2026-08-09", "url": "https://www.rightmove.co.uk/properties/172518572"},
  {"id": 16, "title": "Crail Road, Anstruther", "type": "Casa indipendente", "contract": "sale", "price": 255000, "currency": "GBP", "size": null, "rooms": 2, "baths": null, "floor": null, "year": null, "energy": null, "zone": "East Neuk (Fife, Scozia)", "town": "Anstruther", "addr": "Crail Road, Anstruther, KY10", "lat": 56.226214, "lng": -2.695781, "imgs": ["v1", "i2", "v2"], "feats": [], "desc": "Casa indipendente di 2 camere a Anstruther. Annuncio reale su Rightmove — apri la fonte per foto, superficie e dettagli completi.", "date": "2026-08-09", "url": "https://www.rightmove.co.uk/properties/170223530"},
]
